apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-service
  labels:
    app: postgres-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:alpine
          ports:
            -  containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db-password
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db-name

---

apiVersion: v1
kind: Service
metadata: 
  name:  postgres-service
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432