version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - my-network
    ports:
      - 5439:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env
    networks:
      - my-network
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  postgres-db:

networks:
  my-network:
    driver: bridge
