version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DNS=host=db user=rohith dbname=firstproject password=892328 port=5432 sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=892328
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16